services:
  - type: web
    name: price-comparison-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn 1:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: price-comparison-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && serve -s build
    envVars:
      - key: NODE_VERSION
        value: 16.0.0
      - key: REACT_APP_API_URL
        value: https://price-comparison-backend.onrender.com 